2017-05-10 22:33:45,977 __init__.py[line:19] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections',))),proxy :121.204.165.101:8118
2017-05-10 22:37:06,848 __init__.py[line:19] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', ConnectionAbortedError(10053, '你的主机中的软件中止了一个已建立的连接。', None, 10053, None))),proxy :121.232.146.144:9000
2017-05-10 22:37:16,883 __init__.py[line:19] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001D5A325DEF0>, 'Connection to 121.232.146.170 timed out. (connect timeout=10)')),proxy :121.232.146.170:9000
2017-05-10 22:37:26,900 __init__.py[line:19] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001D5A3288710>, 'Connection to 203.93.0.115 timed out. (connect timeout=10)')),proxy :203.93.0.115:80
2017-05-10 22:37:36,913 __init__.py[line:19] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001D5A3288E10>, 'Connection to 114.99.13.244 timed out. (connect timeout=10)')),proxy :114.99.13.244:9000
2017-05-10 22:37:46,931 __init__.py[line:19] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001D5A3290550>, 'Connection to 117.90.7.246 timed out. (connect timeout=10)')),proxy :117.90.7.246:9000
2017-05-10 22:37:56,062 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',))),proxy :121.232.146.144:9000
2017-05-10 22:38:06,070 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001690D59DEB8>, 'Connection to 121.232.146.170 timed out. (connect timeout=10)')),proxy :121.232.146.170:9000
2017-05-10 22:38:16,082 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001690D5D6710>, 'Connection to 203.93.0.115 timed out. (connect timeout=10)')),proxy :203.93.0.115:80
2017-05-10 22:38:26,092 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001690D5D6E10>, 'Connection to 114.99.13.244 timed out. (connect timeout=10)')),proxy :114.99.13.244:9000
2017-05-10 22:38:36,106 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001690D5DF550>, 'Connection to 117.90.7.246 timed out. (connect timeout=10)')),proxy :117.90.7.246:9000
2017-05-10 22:38:37,156 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001690D5D6B38>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))),proxy :117.90.6.96:9000
2017-05-10 22:38:37,206 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 400 Bad Request',))),proxy :120.27.49.85:8090
2017-05-10 22:38:47,212 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001690D5D65F8>, 'Connection to 183.147.221.156 timed out. (connect timeout=10)')),proxy :183.147.221.156:9000
2017-05-10 22:38:57,231 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001690D59DC18>, 'Connection to 114.99.15.132 timed out. (connect timeout=10)')),proxy :114.99.15.132:9000
2017-05-10 22:39:02,672 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001690D40B780>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))),proxy :121.232.147.186:9000
2017-05-10 22:39:02,952 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 400 Bad Request',))),proxy :202.202.90.20:8080
2017-05-10 22:39:13,002 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',))),proxy :163.125.196.109:9797
2017-05-10 22:39:22,331 __init__.py[line:18] ERROR ("bad handshake: Error([('SSL routines', 'ssl3_get_record', 'wrong version number')],)",),proxy :60.191.170.148:3128
2017-05-10 22:39:23,779 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001690D5DF400>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))),proxy :116.5.47.6:8998
2017-05-10 22:39:24,852 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001690D5E7470>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))),proxy :115.200.167.34:8998
2017-05-10 22:39:25,921 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001690D40B4E0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))),proxy :60.186.41.30:9000
2017-05-10 22:39:35,935 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001690D5DFAC8>, 'Connection to 114.99.5.126 timed out. (connect timeout=10)')),proxy :114.99.5.126:9000
2017-05-10 22:39:36,972 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001690D5E7128>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))),proxy :121.232.145.241:9000
2017-05-10 22:39:46,980 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001690D5E7A20>, 'Connection to 124.206.254.216 timed out. (connect timeout=10)')),proxy :124.206.254.216:3128
2017-05-10 22:39:48,294 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections',))),proxy :222.128.13.94:8081
2017-05-10 22:39:58,300 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001690D5DF8D0>, 'Connection to 117.90.2.4 timed out. (connect timeout=10)')),proxy :117.90.2.4:9000
2017-05-10 22:40:08,451 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001690D59DB38>, 'Connection to 116.252.51.184 timed out. (connect timeout=10)')),proxy :116.252.51.184:8998
2017-05-10 22:40:18,461 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001690D5E4978>, 'Connection to 219.136.13.18 timed out. (connect timeout=10)')),proxy :219.136.13.18:9797
2017-05-10 22:40:19,555 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001690D40B668>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))),proxy :125.79.14.135:8998
2017-05-10 22:40:29,563 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001690D678470>, 'Connection to 117.90.0.50 timed out. (connect timeout=10)')),proxy :117.90.0.50:9000
2017-05-10 22:40:39,715 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',))),proxy :219.136.175.138:9797
2017-05-10 22:40:52,770 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',))),proxy :110.73.10.47:8123
2017-05-10 22:41:02,782 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001690D678C18>, 'Connection to 106.4.134.32 timed out. (connect timeout=10)')),proxy :106.4.134.32:9000
2017-05-10 22:41:14,901 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001690D678160>, 'Connection to 106.4.134.32 timed out. (connect timeout=10)')),proxy :106.4.134.32:9000
2017-05-10 22:41:14,934 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',))),proxy :121.232.147.224:9000
2017-05-10 22:41:23,476 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001690D5E4C50>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))),proxy :121.232.144.173:9000
2017-05-10 22:41:30,312 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001690D59DEB8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))),proxy :117.90.6.136:9000
2017-05-10 22:41:40,316 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001690D678550>, 'Connection to 111.1.3.38 timed out. (connect timeout=10)')),proxy :111.1.3.38:8000
2017-05-10 22:41:50,326 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001690D5E7048>, 'Connection to 114.99.9.82 timed out. (connect timeout=10)')),proxy :114.99.9.82:9000
2017-05-10 22:42:00,341 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001690D67D358>, 'Connection to 117.90.4.95 timed out. (connect timeout=10)')),proxy :117.90.4.95:9000
2017-05-10 22:42:19,407 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',))),proxy :171.38.177.114:8123
2017-05-10 22:42:19,480 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections',))),proxy :182.92.156.85:8118
2017-05-10 22:42:30,699 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001690D678B38>, 'Connection to 122.200.84.19 timed out. (connect timeout=10)')),proxy :122.200.84.19:8080
2017-05-10 22:42:30,770 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections',))),proxy :111.202.121.91:8118
2017-05-10 22:42:41,177 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',))),proxy :61.174.9.237:8090
2017-05-10 22:42:51,182 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001690D5E4EB8>, 'Connection to 115.219.108.53 timed out. (connect timeout=10)')),proxy :115.219.108.53:9000
2017-05-10 22:43:09,371 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',))),proxy :121.204.165.101:8118
2017-05-10 22:44:19,015 __init__.py[line:18] ERROR ("bad handshake: Error([('SSL routines', 'ssl3_get_record', 'wrong version number')],)",),proxy :60.191.170.148:3128
2017-05-10 22:45:56,296 __init__.py[line:18] ERROR ("bad handshake: Error([('SSL routines', 'ssl3_get_record', 'wrong version number')],)",),proxy :60.191.170.148:3128
2017-05-10 22:46:52,546 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000021B8153CE10>, 'Connection to 223.15.29.181 timed out. (connect timeout=10)')),proxy :223.15.29.181:9797
2017-05-10 22:47:02,948 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', timeout('select timed out',))),proxy :14.109.122.253:8998
2017-05-10 22:47:03,136 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', ConnectionAbortedError(10053, '你的主机中的软件中止了一个已建立的连接。', None, 10053, None))),proxy :117.90.1.93:9000
2017-05-10 22:47:13,152 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000021B8153CF60>, 'Connection to 110.73.9.101 timed out. (connect timeout=10)')),proxy :110.73.9.101:8123
2017-05-10 22:47:13,332 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', ConnectionAbortedError(10053, '你的主机中的软件中止了一个已建立的连接。', None, 10053, None))),proxy :121.232.146.144:9000
2017-05-10 22:47:23,340 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000021B81563668>, 'Connection to 121.232.146.170 timed out. (connect timeout=10)')),proxy :121.232.146.170:9000
2017-05-10 22:50:20,531 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001F8D6616CC0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))),proxy :14.109.122.253:8998
2017-05-10 22:52:06,304 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001EA400CDDD8>, 'Connection to 114.99.5.84 timed out. (connect timeout=10)')),proxy :114.99.5.84:9000
2017-05-10 22:52:06,532 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',))),proxy :117.90.0.82:9000
2017-05-10 22:52:16,536 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001EA400E84A8>, 'Connection to 223.15.29.181 timed out. (connect timeout=10)')),proxy :223.15.29.181:9797
2017-05-10 22:52:17,657 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001EA400E8CC0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))),proxy :14.109.122.253:8998
2017-05-10 22:52:27,666 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001EA400F0400>, 'Connection to 117.90.1.93 timed out. (connect timeout=10)')),proxy :117.90.1.93:9000
2017-05-10 22:52:35,803 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', ConnectionAbortedError(10053, '你的主机中的软件中止了一个已建立的连接。', None, 10053, None))),proxy :121.232.146.144:9000
2017-05-10 22:52:45,807 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001EA400E8780>, 'Connection to 121.232.146.170 timed out. (connect timeout=10)')),proxy :121.232.146.170:9000
2017-05-10 22:52:55,811 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001EA400E8438>, 'Connection to 203.93.0.115 timed out. (connect timeout=10)')),proxy :203.93.0.115:80
2017-05-10 22:53:05,815 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001EA400F0898>, 'Connection to 114.99.13.244 timed out. (connect timeout=10)')),proxy :114.99.13.244:9000
2017-05-10 22:53:16,969 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001EA3FF3C400>, 'Connection to 117.90.7.246 timed out. (connect timeout=10)')),proxy :117.90.7.246:9000
2017-05-10 22:53:18,019 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001EA40103048>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))),proxy :117.90.6.96:9000
2017-05-10 22:53:18,405 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 400 Bad Request',))),proxy :120.27.49.85:8090
2017-05-10 22:53:28,412 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001EA3FF3C588>, 'Connection to 183.147.221.156 timed out. (connect timeout=10)')),proxy :183.147.221.156:9000
2017-05-10 22:53:38,421 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001EA400E82B0>, 'Connection to 114.99.15.132 timed out. (connect timeout=10)')),proxy :114.99.15.132:9000
2017-05-10 22:53:39,456 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001EA400E8748>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))),proxy :121.232.147.186:9000
2017-05-10 22:53:39,655 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 400 Bad Request',))),proxy :202.202.90.20:8080
2017-05-10 22:53:49,663 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001EA400E8BE0>, 'Connection to 163.125.196.109 timed out. (connect timeout=10)')),proxy :163.125.196.109:9797
2017-05-10 22:53:56,846 __init__.py[line:18] ERROR ("bad handshake: Error([('SSL routines', 'ssl3_get_record', 'wrong version number')],)",),proxy :60.191.170.148:3128
2017-05-10 22:53:58,320 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001EA40103630>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))),proxy :116.5.47.6:8998
2017-05-10 22:54:01,261 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001EA400E8BE0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))),proxy :115.200.167.34:8998
2017-05-10 22:54:02,317 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001EA400E83C8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))),proxy :60.186.41.30:9000
2017-05-10 22:54:12,321 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001EA3FF1E780>, 'Connection to 114.99.5.126 timed out. (connect timeout=10)')),proxy :114.99.5.126:9000
2017-05-10 22:54:31,339 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',))),proxy :121.232.145.241:9000
2017-05-10 22:54:41,346 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001EA400CDE48>, 'Connection to 124.206.254.216 timed out. (connect timeout=10)')),proxy :124.206.254.216:3128
2017-05-10 22:54:41,424 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections',))),proxy :222.128.13.94:8081
2017-05-10 22:54:51,430 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001EA400F0390>, 'Connection to 117.90.2.4 timed out. (connect timeout=10)')),proxy :117.90.2.4:9000
2017-05-10 22:54:51,476 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))),proxy :222.73.85.74:808
2017-05-10 22:55:01,535 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001EA400F0438>, 'Connection to 116.252.51.184 timed out. (connect timeout=10)')),proxy :116.252.51.184:8998
2017-05-10 22:55:11,542 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001EA400F0320>, 'Connection to 219.136.13.18 timed out. (connect timeout=10)')),proxy :219.136.13.18:9797
2017-05-10 22:55:21,209 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001EA40103128>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))),proxy :125.79.14.135:8998
2017-05-10 22:55:31,214 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001EA401037F0>, 'Connection to 117.90.0.50 timed out. (connect timeout=10)')),proxy :117.90.0.50:9000
2017-05-10 22:55:50,365 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',))),proxy :219.136.175.138:9797
2017-05-10 22:56:00,419 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',))),proxy :110.73.10.47:8123
2017-05-10 22:56:10,426 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001EA401033C8>, 'Connection to 106.4.134.32 timed out. (connect timeout=10)')),proxy :106.4.134.32:9000
2017-05-10 22:56:11,470 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001EA400E8C88>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))),proxy :121.232.147.224:9000
2017-05-10 22:56:20,742 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', ConnectionAbortedError(10053, '你的主机中的软件中止了一个已建立的连接。', None, 10053, None))),proxy :119.254.103.117:80
2017-05-10 22:56:21,782 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001EA400E8128>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))),proxy :121.232.144.173:9000
2017-05-10 22:56:30,939 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001EA400E8048>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))),proxy :117.90.6.136:9000
2017-05-10 22:56:43,744 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001EA40103B38>, 'Connection to 111.1.3.38 timed out. (connect timeout=10)')),proxy :111.1.3.38:8000
2017-05-10 22:56:53,752 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001EA401034A8>, 'Connection to 114.99.9.82 timed out. (connect timeout=10)')),proxy :114.99.9.82:9000
2017-05-10 22:57:03,762 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001EA400F0048>, 'Connection to 117.90.4.95 timed out. (connect timeout=10)')),proxy :117.90.4.95:9000
2017-05-10 22:57:13,769 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001EA400F0DA0>, 'Connection to 171.38.177.114 timed out. (connect timeout=10)')),proxy :171.38.177.114:8123
2017-05-10 22:57:13,847 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections',))),proxy :182.92.156.85:8118
2017-05-10 22:57:23,882 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',))),proxy :122.200.84.19:8080
2017-05-10 22:57:23,942 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections',))),proxy :111.202.121.91:8118
2017-05-10 22:57:34,200 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',))),proxy :61.174.9.237:8090
2017-05-10 22:57:44,209 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001EA3FF1EE48>, 'Connection to 115.219.108.53 timed out. (connect timeout=10)')),proxy :115.219.108.53:9000
2017-05-10 22:57:47,587 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001EA400CD940>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))),proxy :58.47.85.219:8998
2017-05-10 23:03:11,624 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000019BC56E0358>, 'Connection to 61.153.232.218 timed out. (connect timeout=10)')),proxy :61.153.232.218:8080
2017-05-10 23:03:21,632 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000019BC56E0940>, 'Connection to 182.107.5.194 timed out. (connect timeout=10)')),proxy :182.107.5.194:9000
2017-05-10 23:03:34,250 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000019BC56F35F8>, 'Connection to 114.99.5.84 timed out. (connect timeout=10)')),proxy :114.99.5.84:9000
2017-05-10 23:03:44,252 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000019BC56F3978>, 'Connection to 117.90.0.82 timed out. (connect timeout=10)')),proxy :117.90.0.82:9000
2017-05-10 23:03:54,261 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000019BC56E09B0>, 'Connection to 223.15.29.181 timed out. (connect timeout=10)')),proxy :223.15.29.181:9797
2017-05-10 23:03:55,574 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000019BC56E0550>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))),proxy :14.109.122.253:8998
2017-05-10 23:03:56,618 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000019BC56F3128>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))),proxy :117.90.1.93:9000
2017-05-10 23:04:06,621 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000019BC56D4E48>, 'Connection to 110.73.9.101 timed out. (connect timeout=10)')),proxy :110.73.9.101:8123
2017-05-10 23:04:07,660 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000019BC5703358>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))),proxy :121.232.146.144:9000
2017-05-10 23:04:09,862 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000019BC56E00F0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))),proxy :121.232.146.144:9000
2017-05-10 23:04:19,865 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000019BC56E0908>, 'Connection to 121.232.146.170 timed out. (connect timeout=10)')),proxy :121.232.146.170:9000
2017-05-10 23:04:29,872 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000019BC56D4A90>, 'Connection to 203.93.0.115 timed out. (connect timeout=10)')),proxy :203.93.0.115:80
2017-05-10 23:04:39,879 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000019BC553F668>, 'Connection to 114.99.13.244 timed out. (connect timeout=10)')),proxy :114.99.13.244:9000
2017-05-10 23:04:49,888 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000019BC5703780>, 'Connection to 117.90.7.246 timed out. (connect timeout=10)')),proxy :117.90.7.246:9000
2017-05-10 23:04:59,895 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000019BC5703D30>, 'Connection to 117.90.6.96 timed out. (connect timeout=10)')),proxy :117.90.6.96:9000
2017-05-10 23:04:59,943 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 400 Bad Request',))),proxy :120.27.49.85:8090
2017-05-10 23:05:09,951 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000019BC553F6A0>, 'Connection to 183.147.221.156 timed out. (connect timeout=10)')),proxy :183.147.221.156:9000
2017-05-10 23:05:19,955 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000019BC40F2C18>, 'Connection to 114.99.15.132 timed out. (connect timeout=10)')),proxy :114.99.15.132:9000
2017-05-10 23:05:21,048 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000019BC56E0CF8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))),proxy :121.232.147.186:9000
2017-05-10 23:05:23,429 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 400 Bad Request',))),proxy :202.202.90.20:8080
2017-05-10 23:05:35,882 __init__.py[line:18] ERROR ("bad handshake: Error([('SSL routines', 'ssl3_get_record', 'wrong version number')],)",),proxy :60.191.170.148:3128
2017-05-10 23:05:37,320 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000019BC56E0438>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))),proxy :116.5.47.6:8998
2017-05-10 23:05:47,325 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000019BC5703358>, 'Connection to 115.200.167.34 timed out. (connect timeout=10)')),proxy :115.200.167.34:8998
2017-05-10 23:05:48,418 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000019BC5703390>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))),proxy :60.186.41.30:9000
2017-05-10 23:05:58,420 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000019BC56F39E8>, 'Connection to 114.99.5.126 timed out. (connect timeout=10)')),proxy :114.99.5.126:9000
2017-05-10 23:05:59,526 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000019BC56F3A58>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))),proxy :121.232.145.241:9000
2017-05-10 23:06:09,531 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000019BC553F978>, 'Connection to 124.206.254.216 timed out. (connect timeout=10)')),proxy :124.206.254.216:3128
2017-05-10 23:06:24,281 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000019BC2319198>, 'Connection to 117.90.2.4 timed out. (connect timeout=10)')),proxy :117.90.2.4:9000
2017-05-10 23:06:34,364 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000019BC553F860>, 'Connection to 116.252.51.184 timed out. (connect timeout=10)')),proxy :116.252.51.184:8998
2017-05-10 23:06:52,873 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', ConnectionAbortedError(10053, '你的主机中的软件中止了一个已建立的连接。', None, 10053, None))),proxy :219.136.13.18:9797
2017-05-10 23:06:53,974 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000019BC57035C0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))),proxy :125.79.14.135:8998
2017-05-10 23:06:55,018 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000019BC5703940>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))),proxy :117.90.0.50:9000
2017-05-10 23:07:05,021 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000019BC56E0400>, 'Connection to 219.136.175.138 timed out. (connect timeout=10)')),proxy :219.136.175.138:9797
2017-05-10 23:07:15,075 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',))),proxy :110.73.10.47:8123
2017-05-10 23:07:25,085 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000019BC56E0320>, 'Connection to 106.4.134.32 timed out. (connect timeout=10)')),proxy :106.4.134.32:9000
2017-05-10 23:07:26,128 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000019BC57899B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))),proxy :121.232.147.224:9000
2017-05-10 23:07:38,475 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000019BC56E0B00>, 'Connection to 121.232.147.224 timed out. (connect timeout=10)')),proxy :121.232.147.224:9000
2017-05-10 23:07:48,484 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000019BC56D4CF8>, 'Connection to 119.254.103.117 timed out. (connect timeout=10)')),proxy :119.254.103.117:80
2017-05-10 23:07:48,510 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', ConnectionAbortedError(10053, '你的主机中的软件中止了一个已建立的连接。', None, 10053, None))),proxy :121.232.144.173:9000
2017-05-10 23:07:49,773 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000019BC5703E80>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))),proxy :117.90.6.136:9000
2017-05-10 23:07:49,826 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 400 Bad Request',))),proxy :111.1.3.38:8000
2017-05-10 23:07:59,833 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000019BC5703C50>, 'Connection to 114.99.9.82 timed out. (connect timeout=10)')),proxy :114.99.9.82:9000
2017-05-10 23:08:09,840 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000019BC551FC18>, 'Connection to 117.90.4.95 timed out. (connect timeout=10)')),proxy :117.90.4.95:9000
2017-05-10 23:08:19,905 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',))),proxy :171.38.177.114:8123
2017-05-10 23:08:20,029 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections',))),proxy :182.92.156.85:8118
2017-05-10 23:08:30,066 __init__.py[line:18] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',))),proxy :122.200.84.19:8080
